// AUTO-GENERATED by @lovable.dev/mcp-js — do not edit. Regenerated by the Vite plugin.
// To take ownership, delete this banner line; the plugin then leaves the file alone.
// supabase function: mcp
// Bundled from src/lib/mcp/index.ts by @lovable.dev/mcp-js.
// src/lib/mcp/index.ts
import { auth, defineMcp } from "npm:@lovable.dev/mcp-js@0.20.0";

// src/lib/mcp/tools/list-opportunities.ts
import { createClient } from "npm:@supabase/supabase-js@^2.103.1";
import { defineTool } from "npm:@lovable.dev/mcp-js@0.20.0";
import { z } from "npm:zod@^3.25.76";
function sb(ctx) {
  return createClient(process.env.SUPABASE_URL, process.env.SUPABASE_PUBLISHABLE_KEY, {
    global: { headers: { Authorization: `Bearer ${ctx.getToken()}` } },
    auth: { persistSession: false, autoRefreshToken: false }
  });
}
var list_opportunities_default = defineTool({
  name: "list_opportunities",
  title: "List opportunities",
  description: "List sales opportunities visible to the signed-in user. Optional filters by stage and text search on name/company.",
  inputSchema: {
    stage: z.string().optional().describe("Filter by stage slug (e.g. novo_lead, negociacao, fechado_won)."),
    search: z.string().optional().describe("Case-insensitive substring match against name and company."),
    limit: z.number().int().min(1).max(200).optional().describe("Max rows to return (default 50).")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ stage, search, limit }, ctx) => {
    if (!ctx.isAuthenticated()) {
      return { content: [{ type: "text", text: "Not authenticated" }], isError: true };
    }
    let q = sb(ctx).from("opportunities").select("id, name, company, stage, estimated_mrr, estimated_tpv, probability, consultant_id, created_at, closed_at, converted_at").order("created_at", { ascending: false }).limit(limit ?? 50);
    if (stage) q = q.eq("stage", stage);
    if (search) q = q.or(`name.ilike.%${search}%,company.ilike.%${search}%`);
    const { data, error } = await q;
    if (error) return { content: [{ type: "text", text: error.message }], isError: true };
    return {
      content: [{ type: "text", text: JSON.stringify(data ?? []) }],
      structuredContent: { rows: data ?? [] }
    };
  }
});

// src/lib/mcp/tools/get-opportunity.ts
import { createClient as createClient2 } from "npm:@supabase/supabase-js@^2.103.1";
import { defineTool as defineTool2 } from "npm:@lovable.dev/mcp-js@0.20.0";
import { z as z2 } from "npm:zod@^3.25.76";
function sb2(ctx) {
  return createClient2(process.env.SUPABASE_URL, process.env.SUPABASE_PUBLISHABLE_KEY, {
    global: { headers: { Authorization: `Bearer ${ctx.getToken()}` } },
    auth: { persistSession: false, autoRefreshToken: false }
  });
}
var get_opportunity_default = defineTool2({
  name: "get_opportunity",
  title: "Get opportunity",
  description: "Fetch a single opportunity by id, including all fields the signed-in user is allowed to see.",
  inputSchema: {
    id: z2.string().uuid().describe("Opportunity id (UUID).")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ id }, ctx) => {
    if (!ctx.isAuthenticated()) {
      return { content: [{ type: "text", text: "Not authenticated" }], isError: true };
    }
    const { data, error } = await sb2(ctx).from("opportunities").select("*").eq("id", id).maybeSingle();
    if (error) return { content: [{ type: "text", text: error.message }], isError: true };
    if (!data) return { content: [{ type: "text", text: "Not found" }], isError: true };
    return {
      content: [{ type: "text", text: JSON.stringify(data) }],
      structuredContent: { opportunity: data }
    };
  }
});

// src/lib/mcp/tools/list-commissions.ts
import { createClient as createClient3 } from "npm:@supabase/supabase-js@^2.103.1";
import { defineTool as defineTool3 } from "npm:@lovable.dev/mcp-js@0.20.0";
import { z as z3 } from "npm:zod@^3.25.76";
function sb3(ctx) {
  return createClient3(process.env.SUPABASE_URL, process.env.SUPABASE_PUBLISHABLE_KEY, {
    global: { headers: { Authorization: `Bearer ${ctx.getToken()}` } },
    auth: { persistSession: false, autoRefreshToken: false }
  });
}
var list_commissions_default = defineTool3({
  name: "list_commissions",
  title: "List commissions",
  description: "List commissions visible to the signed-in user. Optional filters by status and payment month (YYYY-MM).",
  inputSchema: {
    status: z3.string().optional().describe("Filter by status (e.g. provisioned, paid, canceled)."),
    payment_month: z3.string().regex(/^\d{4}-\d{2}$/).optional().describe("Filter by payment month in YYYY-MM format."),
    limit: z3.number().int().min(1).max(500).optional().describe("Max rows to return (default 100).")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ status, payment_month, limit }, ctx) => {
    if (!ctx.isAuthenticated()) {
      return { content: [{ type: "text", text: "Not authenticated" }], isError: true };
    }
    let q = sb3(ctx).from("commissions").select("id, opportunity_id, seller_id, product_id, sale_date, payment_month, commission_amount, type, status").order("payment_month", { ascending: false }).limit(limit ?? 100);
    if (status) q = q.eq("status", status);
    if (payment_month) {
      const start = `${payment_month}-01`;
      const [y, m] = payment_month.split("-").map(Number);
      const nextMonth = m === 12 ? `${y + 1}-01-01` : `${y}-${String(m + 1).padStart(2, "0")}-01`;
      q = q.gte("payment_month", start).lt("payment_month", nextMonth);
    }
    const { data, error } = await q;
    if (error) return { content: [{ type: "text", text: error.message }], isError: true };
    return {
      content: [{ type: "text", text: JSON.stringify(data ?? []) }],
      structuredContent: { rows: data ?? [] }
    };
  }
});

// src/lib/mcp/tools/list-chatwoot-conversations.ts
import { createClient as createClient4 } from "npm:@supabase/supabase-js@^2.103.1";
import { defineTool as defineTool4 } from "npm:@lovable.dev/mcp-js@0.20.0";
import { z as z4 } from "npm:zod@^3.25.76";
function sb4(ctx) {
  return createClient4(process.env.SUPABASE_URL, process.env.SUPABASE_PUBLISHABLE_KEY, {
    global: { headers: { Authorization: `Bearer ${ctx.getToken()}` } },
    auth: { persistSession: false, autoRefreshToken: false }
  });
}
var list_chatwoot_conversations_default = defineTool4({
  name: "list_chatwoot_conversations",
  title: "List Chatwoot conversations",
  description: "List recent Chatwoot conversations synced into Yampa. Optional filters by status and contact email or phone.",
  inputSchema: {
    status: z4.string().optional().describe("Conversation status (e.g. open, resolved, pending)."),
    contact: z4.string().optional().describe("Substring match against contact email or phone."),
    limit: z4.number().int().min(1).max(200).optional().describe("Max rows to return (default 50).")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ status, contact, limit }, ctx) => {
    if (!ctx.isAuthenticated()) {
      return { content: [{ type: "text", text: "Not authenticated" }], isError: true };
    }
    let q = sb4(ctx).from("chatwoot_conversations").select(
      "chatwoot_conversation_id, status, tabulacao_atendimento, contact_email, contact_phone, assignee_email, labels, last_message_at, opened_at"
    ).order("last_message_at", { ascending: false, nullsFirst: false }).limit(limit ?? 50);
    if (status) q = q.eq("status", status);
    if (contact) q = q.or(`contact_email.ilike.%${contact}%,contact_phone.ilike.%${contact}%`);
    const { data, error } = await q;
    if (error) return { content: [{ type: "text", text: error.message }], isError: true };
    return {
      content: [{ type: "text", text: JSON.stringify(data ?? []) }],
      structuredContent: { rows: data ?? [] }
    };
  }
});

// src/lib/mcp/tools/whoami.ts
import { defineTool as defineTool5 } from "npm:@lovable.dev/mcp-js@0.20.0";
var whoami_default = defineTool5({
  name: "whoami",
  title: "Who am I",
  description: "Return the identity of the signed-in Yampa user backing this MCP connection.",
  inputSchema: {},
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: (_input, ctx) => {
    if (!ctx.isAuthenticated()) {
      return { content: [{ type: "text", text: "Not authenticated" }], isError: true };
    }
    const info = {
      user_id: ctx.getUserId(),
      email: ctx.getUserEmail(),
      client_id: ctx.getClientId()
    };
    return {
      content: [{ type: "text", text: JSON.stringify(info) }],
      structuredContent: info
    };
  }
});

// src/lib/mcp/index.ts
var projectRef = "wdtdpyibiroufejijsmw";
var mcp_default = defineMcp({
  name: "yampa-mcp",
  title: "Yampa CRM",
  version: "0.1.0",
  instructions: "Tools for the Yampa sales CRM. Use `whoami` to confirm identity, `list_opportunities` and `get_opportunity` for the sales pipeline, `list_commissions` for seller commissions, and `list_chatwoot_conversations` for recent support/sales conversations. All reads run as the signed-in user via Supabase RLS.",
  auth: auth.oauth.issuer({
    issuer: `https://${projectRef}.supabase.co/auth/v1`,
    acceptedAudiences: "authenticated"
  }),
  tools: [whoami_default, list_opportunities_default, get_opportunity_default, list_commissions_default, list_chatwoot_conversations_default]
});

// lovable-mcp-supabase-entry.ts
import { createSupabaseHandler } from "npm:@lovable.dev/mcp-js@0.20.0/stacks/supabase";
Deno.serve(createSupabaseHandler(mcp_default, { functionName: "mcp" }));
