ALTER TABLE public.stripe_prices ADD CONSTRAINT stripe_prices_price_id_key UNIQUE (price_id);

INSERT INTO public.stripe_prices (price_id, product_name, plan_name, price_name, area, mrr) VALUES
('price_1LJI9LFuYia200V0mEqH9eHL', 'YampaFin', '+Lucro', 'Parceria Fernando | +Lucro Anual', 'Parceria', 198.5),
('price_1LVxelFuYia200V0bcnypJBQ', 'YampaFin', '+Controle', 'Parceria Fernando | +Controle Anual', 'Parceria', 96.58),
('price_1OC0njFuYia200V05JzIdhRq', 'YampaFin', '+Controle', 'Plataforma +Controle Anual', 'Produto', 96.58),
('price_1LX7GHFuYia200V0OTNEoijm', 'YampaFin', '+Controle', 'Parceria Fernando | +Controle Anual', 'Parceria', 84.51),
('price_1OC0lzFuYia200V0rl4PQlj7', 'YampaFin', '+Controle', 'Plataforma +Controle Anual', 'Produto', 84.51),
('price_1OHQ9YFuYia200V07TnRccKt', 'YampaFin', '+Controle', 'SALES +Controle Anual a vista', 'Sales', 84.51),
('price_1LVxfaFuYia200V0zh3FC58o', 'YampaFin', '+Controle', 'Parceria Mabel | +Controle Anual Mensalizado', 'Parceria', 87.92),
('price_1LX7IEFuYia200V0lSxkXFv3', 'YampaFin', '+Lucro', 'Parceria Mabel | +Lucro Anual A vista', 'Parceria', 161.78),
('price_1OCO8eFuYia200V0JMOuOSYd', 'YampaFin', '+Sucesso', 'CS +Sucesso para Vitalícios Anual Mensalizado', 'CX', 407.59),
('price_1OCR11FuYia200V09ByPbmE8', 'YampaFin', '+Sucesso', 'CS +Sucesso para Vitalícios Anual', 'CX', 347.48),
('price_1OC0vLFuYia200V0VDJcvMLB', 'YampaFin', '+Sucesso', 'Plataforma +Sucesso para Vitalícios Anual', 'Produto', 209.09),
('price_1OC0wIFuYia200V0Vptub0m8', 'YampaFin', '+Sucesso', 'Plataforma +Sucesso para Vitalícios Anual', 'Produto', 177.67),
('price_1LJI84FuYia200V0YXRIZRMX', 'YampaFin', '+Lucro', 'Parceria Ronielly | +Lucro Anual Mensalizado', 'Parceria', 189.77),
('price_1N85eoFuYia200V0Ox6mP28z', 'YampaFin', '+Sucesso', 'Parceria Sebrae | +Sucesso Mensal', 'Parceria', 574.73),
('price_1N85g1FuYia200V0ZyhNOalN', 'YampaFin', '+Sucesso', 'Parceria Sebrae | +Sucesso Anual Mensalizado', 'Parceria', 389.67),
('price_1N85h9FuYia200V0sY6cTmoa', 'YampaFin', '+Sucesso', 'Parceria Sebrae | +Sucesso Anual A vista', 'Parceria', 332.2),
('price_1OVF5yDrhWjWTprTFuwOUwSg', 'YampaFin', '+Sucesso', 'Plataforma +Sucesso Anual', 'Produto', 407.59),
('price_1OVF5vDrhWjWTprTTEdtyt8S', 'YampaFin', '+Sucesso', 'Plataforma +Sucesso Anual', 'Produto', 347.48),
('price_1OVF5lDrhWjWTprTQUGk6eZf', 'YampaFin', '+Lucro', 'Plataforma +Lucro Anual', 'Produto', 198.5),
('price_1OVF5hDrhWjWTprTGOhqvj52', 'YampaFin', '+Lucro', 'Plataforma +Lucro Anual', 'Produto', 169.81),
('price_1OVF5vDrhWjWTprTDYuW29Zd', 'YampaFin', '+Sucesso', 'CS +Sucesso para Vitalícios Anual (Oferta 2024)', 'CX', 347.48),
('price_1OVF5lDrhWjWTprTyw9V1PxF', 'YampaFin', '+Lucro', 'Parceria Karina Ikeda - +Lucro Anual Mensalizado', 'Parceria', 389.67),
('price_1OVF5MDrhWjWTprTEMWFyd89', 'YampaFin', '+Controle', 'CS +Controle Mensal (Migração HM 79,9)', 'CX', 108.65),
('price_1OVF5TDrhWjWTprTvKnbCPhL', 'YampaFin', '+Controle', 'CS +Controle Anual a vista (Migração HM 790,9)', 'CX', 76.05),
('price_1OrJ3XDrhWjWTprTAkyvgRQl', 'YampaFin', '+Lucro', 'MKT +Lucro - Freetrial com cartão - Campanhas e Make', 'Marketing', 198.5),
('price_1OCQnOFuYia200V0PIw9Dke9', 'YampaFin', '+Controle', 'Parceria Taurus (Mentores da 4blue) | +Controle Anual Mensalizado', 'Parceria', 87.92),
('price_1OCO9ZFuYia200V0oum9BDmw', 'YampaFin', '+Lucro', 'Parceria Taurus (Mentores da 4blue) | +Lucro Anual Mensalizado', 'Parceria', 189.77),
('price_1OVF5dDrhWjWTprTyfzBqvjf', 'YampaFin', '+Lucro', 'yampa +Lucro Mensal 2024', 'Produto', 292.78),
('price_1OVF5TDrhWjWTprTg0xgXOud', 'YampaFin', '+Controle', 'Plataforma +Controle Anual Migração HM474', 'Produto', 39.5),
('price_1OVF5dDrhWjWTprTgfQHG7q9', 'YampaFin', '+Lucro', 'CS +Lucro Mensal (Multiplas)', 'CX', 292.78),
('price_1LQEUxFuYia200V0HGhqTM0H', 'YampaFin', '+Controle', 'CS +Controle Anual Mensalizado (Retenção Asaas)', 'CX', 96.58),
('price_1OVF5yDrhWjWTprTnJOd4ByO', 'YampaFin', '+Sucesso', 'Parceria LÚCIO LOPES', 'Parceria', 396.8),
('price_1OC0jGFuYia200V0MbGRXvCm', 'YampaFin', '+Controle', 'Plataforma +Controle Mensal', 'Produto', 120.73),
('price_1OC0reFuYia200V04icCfkHu', 'YampaFin', '+Lucro', 'Plataforma +Lucro Mensal', 'Produto', 292.78),
('price_1OVF5sDrhWjWTprTfUpv99io', 'YampaFin', '+Sucesso', 'Plataforma +Sucesso Mensal', 'Produto', 601.17),
('price_1OVF5YDrhWjWTprTV7q68Gak', 'YampaFin', '+Controle', 'CS +Controle Anual Mensalizado (Multiplas)', 'CX', 96.58),
('price_1RTlTZDrhWjWTprTX21N7hIh', 'YampaFin', '+Controle', 'y +Controle Mensal', 'Produto', 120.17),
('price_1RTlZoDrhWjWTprTsWJzI2yw', 'YampaFin', '+Lucro', 'y +Lucro Anual (12 meses)', 'Produto', 198.5),
('price_1RTlT9DrhWjWTprTUKwnDtin', 'YampaFin', '+Controle', 'y +Controle Mensal', 'Produto', 120.17),
('price_1RTlUkDrhWjWTprTprmuehXi', 'YampaFin', '+Controle', 'y +Controle Anual', 'Produto', 107.0),
('price_1RTlXkDrhWjWTprTQsJmKHcr', 'YampaFin', '+Lucro', 'y +Lucro Mensal', 'Produto', 279.5),
('price_1RTlZxDrhWjWTprTJspEymTE', 'YampaFin', '+Lucro', 'y +Lucro Anual (12 meses)', 'Produto', 198.5)
ON CONFLICT (price_id) DO UPDATE SET
  product_name = EXCLUDED.product_name,
  plan_name = EXCLUDED.plan_name,
  price_name = EXCLUDED.price_name,
  area = EXCLUDED.area,
  mrr = EXCLUDED.mrr,
  updated_at = now();